core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.feed, name='index'),
    path('feed', views.feed, name='feed'),
    path('store', views.store, name='store'),

    path('product/<slug>', views.product, name='product'),
    path('vendor/<slug>', views.vendor, name='vendor'),
    path('vendor/<slug>/feed', views.vendor_feed, name='vendor_feed'),
    path('vendor/<slug>/store', views.vendor_store, name='vendor_store'),
    path('vendor/<slug>/about', views.vendor_about, name='vendor_about'),

    path('search', views.search_view, name='search'),

    path('post/<int:id>', views.post, name = 'post'),

    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('cart/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund'),

    path('order/<ref_code>', views.OrderView.as_view(), name='order'),
    path('cancel-order/<ref_code>', views.cancel_order, name='cancel_order'),

    path('account/', views.account, name='account'),
    path('account/<str:page>', views.account_page, name='account_page'),
    path('change_password', views.change_password, name='change_password'),
    path('change_preferences', views.change_preferences, name='change_preferences'),
    path('delete_account', views.delete_account, name='delete_account'),

    path('landing/', views.landing, name='landing'),
    path('driver_signup/', views.driver_signup, name='driver_signup'),

    path('read-notifications', views.read_notifications, name = 'read_notifications'),
    path('clear-notifications', views.clear_notifications, name = 'clear_notifications'),

    path('follow-action/<slug>', views.follow_action, name = 'follow-action'),
    path('like-action/<int:id>', views.like_action, name = 'like-action'),
    path('comment', views.comment, name = 'comment'),
    path('comments/', views.comments, name = 'comments'),
    path('get_feed_posts/', views.get_feed_posts, name = 'get_feed_posts'),
]

simntx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace = 'core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('db/', include('dashboards.urls', namespace = 'dashboards')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/blocks/comment.html
{% load tags %}

<div class = "post-comment">
	<div class = "comment-image">
		<p>{{ comment.user.first_name.0 }}</p>
	</div>
	<div class = "comment-main">
		<div class = "comment-info">
			<p class = "comment-name">{{ comment.user.first_name }} {{ comment.user.last_name }}</p>
			
			<p class = "comment-posted" title = "{{ comment.posted }}">{% get_normal_time comment.posted %}</p>
		</div>
		<p class = "comment-text">{{ comment.text }}</p>
	</div>
</div>

templates/blocks/follow-container.html
{% load tags %}

<div class = "follow-container">
	<input class = "vendor-slug" type = "text" value = "{{ vendor.slug }}" hidden style = "display: none;">

	{% if show_count %}
		<div class = "follow-count">
			<span style = "display: flex; align-items: baseline;">
				<p class = "follower-count">{% get_follower_count vendor %}</p>
			</span>
		</div>
	{% endif %}
	
	{% if vendor in user.userprofile.following.all %}
		<div class = "follow following">
			Following
		</div>
	{% else %}
		<div class = "follow">
			Follow
		</div>
	{% endif %}
</div>

templates/blocks/footer.html
<div id = "footer">
	<div id = "social-media">
		<div class = "safe-div"></div>
	</div>
	<div id = "legal-info">
		<div class = "safe-div"></div>
	</div>
</div>

templates/blocks/listing_item.html
{% load staticfiles %}

{% if vendor == True %}
	
	<div class = "listing-item vendor {% if grid_item %}grid-item{% endif %}" {% if height %}style = "height: {{ height }};"{% endif %}>
		<a class = "listing-image-container" href = "{{ item.get_absolute_url }}">
			<div class = "listing-image" {% if item.cover_image %}style = "background-image: url({{item.cover_image.url}})"{% endif %}>

			</div>
		</a>
		<div class = "listing-info">
			<div class = "listing-main">
				<span class = "listing-title">
					<a href = "{{ item.get_absolute_url }}">{{ item.title }}</a>
					{% include 'blocks/follow-container.html' with vendor=item show_count=None %}
				</span>
				<span class = "vendor-address">
					<img src = "{% static 'img/icons/location-color-48.png' %}">
					<p>{{ item.address.street_address }}</p>
				</span>
			</div>
		</div>
	</div>
	
{% else %}

	<div class = "listing-item product {% if grid_item %}grid-item{% endif %}" {% if height %}style = "height: {{ height }};"{% endif %}>
		<a class = "listing-image-container" href = "{{ item.get_absolute_url }}">
			<div class = "listing-image" style = "background-image: url({{item.image.url}})">
				
			</div>
		</a>
		<div class = "listing-info">
			<div class = "listing-main">
				<span class = "listing-title">
					<a href = "{{ item.get_absolute_url }}">
						<span>{{ item.title }}</span>
					</a>
				</span>
				<p class = "listing-price price">${{ item.price }}</p>
			</div>
			<div class = "listing-other">
				<a href = "{{ item.vendor.get_absolute_url }}">
					<p class = "listing-vendor">
						{% if show_promotions and item.promotion %}
							{% include 'blocks/promoted-tag.html' %}
						{% endif %}
						
						<span>{{ item.vendor.title }}</span></p>
				</a>
			</div>
		</div>
	</div>

{% endif %}

templates/blocks/nav.html
{% load staticfiles %}

{% load tags %}

<div id = "nav">
	<div id = "nav-first-panel">
		<div id = "nav-left">
			<img id = "left-panel-expand" src = "{% static 'img/icons/menu-48.png' %}">
			<a href = "{% url 'core:index' %}">
				<img id = "logo" src = "{% static 'img/logo.png' %}">
			</a>
		</div>
		<div id = "nav-right">
			{% url 'core:search' as page %}
			{% include 'blocks/searchbar.html' with page=page search_bar=True form_id='search-form' %}
		</div>
	</div>
	<div id = "nav-second-panel">
		{% if user.is_authenticated %}
			<div class = "nav-button" id = "notification-container">
				<img src = "{% static 'img/icons/bell-white-48.png' %}">
				
				{% get_notification_count user as noti_count %}
				{% if noti_count > 0 %}
					<div class = "item-count-badge" style = "background-color: var(--light-red);">{{ noti_count }}</div>
				{% endif %}
				
				<div class = "dropdown-container">
					<div class = "header">
						<p class = "title">Notifications</p>
						<p class = "link" id = "clear-notifications" style = "text-align: end;">Clear All</p>
					</div>
					
					{% get_notifications user as notifications %}
					{% for noti in notifications %}
						<a class = "notification-container" href = "{{ noti.link }}">
							<div class = "notification">
								<div class = "noti-left">
									<div class = "noti-read {% if noti.read %}read{% endif %}"></div>
								</div>
								<div class = "noti-right">
									<p class = "noti-text">{{ noti.text|safe }}</p>
									
									{% get_normal_time noti.created as noti_time %}
									<p class = "noti-time">{{ noti_time }}</p>
								</div>
							</div>
						</a>
					{% endfor %}
				</div>
			</div>
			<div class = "nav-button">
				<a href = "{% url 'core:order-summary' %}" style = "display: flex; align-items: flex-end;">
					<img src = "{% static 'img/icons/cart-white-48.png' %}">
				</a>
				
				{% get_cart_count user as cart_count %}
				{% if cart_count > 0 %}
					<div class = "item-count-badge">{{ cart_count }}</div>
				{% endif %}
			</div>
			<div class = "nav-button user-button">
				<p class = "user-initial">{{ user.first_name.0 }}</p>
				<div class = "dropdown-container">
					<div id = "user-info">
						<div class = "nav-button user-button">
							<p class = "user-initial">{{ user.first_name.0 }}</p>
						</div>
						<p id = "user-name">{{ user.first_name }} {{ user.last_name }}</p>
					</div>
					<div class = "left-panel-group">
						<div class = "links">
							<a href = "{% url 'core:account_page' 'orders' %}">
								<div class = "link">
									<div class = "link-image">
										<img src = "{% static 'img/icons/products-color-48.png' %}">
									</div>
									<p>Orders</p>
								</div>
							</a>
							<a href = "{% url 'core:account' %}">
								<div class = "link">
									<div class = "link-image">
										<img src = "{% static 'img/icons/settings-color-48.png' %}">
									</div>
									<p>Settings</p>
								</div>
							</a>
							<form id = "logout-form" action = "{% url 'account_logout' %}" method = "POST">
								{% csrf_token %}
								
								<div class = "link">
									<div class = "link-image">
										<img src = "{% static 'img/icons/logout-color-64.png' %}">
									</div>
									<p>Logout</p>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		{% else %}
			<div id = "account-links">
				<a href = "{% url 'account_login' %}" style = "margin-right: 10px;">Login</a>
				<a href = "{% url 'account_signup' %}">Sign Up</a>
			</div>
		{% endif %}
	</div>
	
	{% if messages %}
		<div class = "messages">
			{% for message in messages %}
				<div {% if message.tags %}class="message {{ message.tags }}"{% endif %}>
					<p>{{ message }}</p>
					<div class = "close">
						<img src = "{% static 'img/icons/delete-white-48.png' %}">
					</div>
				</div>
			{% endfor %}
		</div>
	{% endif %}
</div>

templates/blocks/order_keep.html
<div class = "header" style = "display: flex; align-items: baseline;">
	<p class = "content-title large">Keep</p>
</div>

<div class = "cart-final-prices">
	{% if vendor_view %}
		<div class = "cart-item">
			<div class = "item-details">
				<p class = "title">Delivery Fee</p>
			</div>
			<p class = "price">-$5.00</p>
		</div>
		<div class = "cart-item">
			<div class = "item-details">
				<p class = "title">Simntx Fee</p>
			</div>
			<p class = "price">-${{ order.get_simntx_keep }}</p>
		</div>
		<div class = "cart-total">
			<p class = "title">Vendor Keep (USD)</p>
			<p class = "price">${{ order.get_vendor_keep }}</p>
		</div>
	{% else %}
		<div class = "cart-total">
			<p class = "title">Driver Keep (USD)</p>
			<p class = "price">$5.00</p>
		</div>
	{% endif %}
</div>

{% if DISPLAY_COUPON_FORM %}
	<form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
		{% csrf_token %}
		
		<div class = "form-field row">
			<input id = "id_code" class = "field-input" type = "text" name = "code" placeholder = "Promo code">
			<input class = "form-submit" type = "submit" value = "Apply">
		</div>
	</form>
{% endif %}

templates/blocks/post.html
{% load staticfiles %}
{% load tags %}

<div class = "post content-panel">
	<input class = "post-id" type = "text" value = "{{ post.id }}" hidden>
	<input class = "comment-index" type = "text" value = "0" hidden>
	<div class = "post-header">
		<a href = "{{ post.vendor.get_absolute_url }}">
			<img class = "post-vendor-image" src = "{{ post.vendor.profile_image.url }}">
		</a>
		<div class = "post-info">
			<a href = "{{ post.vendor.get_absolute_url }}">
				<p class = "post-vendor underline">{{ post.vendor.title }}</p>
			</a>
			<a href = "{% url 'core:post' post.id %}">
				<p class = "post-date underline" title = "{{ post.posted }}">
					{% if post.promoted %}
						{% include 'blocks/promoted-tag.html' %}
					{% endif %}
					
					<span>{% get_normal_time post.posted %}</span>
				</p>
			</a>
		</div>
	</div>
	<p class = "post-text">{{ post.text }}</p>
	
	{% if post.links.all|length > 0 %}
		<div class = "links">
			{% for link in post.links.all %}
				<a class = "post-link" target="_blank" href = "{{ link.link }}">
					<img src = "{% static 'img/icons/link-48.png' %}">
					<span style = "display: flex; align-items: baseline;">
						<p class = "title">{{ link.title }}</p>
						<p class = "url">{{ link.link }}</p>
					</span>
				</a>
			{% endfor %}
		</div>
	{% endif %}
	
	{% if post.images.all|length > 0 %}
		<div class = "images">
			{% for image in post.images.all %}
				<a class = "post-image" target="_blank" href = "{{ image.image.url }}">
					<img src = "{{ image.image.url }}">
				</a>
			{% endfor %}
		</div>
	{% endif %}
	
	<div class = "action-bar">
		<div class = "post-actions">
			<div class = "like-post post-action">
				{% if post in user.userprofile.liked_posts.all %}
					<img src = "{% static 'img/icons/heart-color-48.png' %}">
				{% else %}
					<img src = "{% static 'img/icons/heart-hollow-48.png' %}">
				{% endif %}
				
				{% get_like_count post as like_count %}
				<p>{{ like_count }}</p>
			</div>
			<div class = "comment-post post-action">
				<img src = "{% static 'img/icons/comment-hollow-48.png' %}">

				{% get_comment_count post as comment_count %}
				<a href>
					<p>{{ comment_count }}</p>
				</a>
			</div>
		</div>
	</div>
		
	<div class = "comments-container">
		{% if comment_count > 0 %}
			{% if comment_count > 1 %}
				<p class = "underline load-more-comments" style = "cursor: pointer; font-size: 14px; margin-bottom: 15px;">load more comments</p>
			{% endif %}
			
			<div class = "post-comments">
				{% get_latest_comment post as comment %}
				{% include 'blocks/comment.html' with comment=comment %}
			</div>
		{% endif %}	
		
		<div class = "add-comment">
			<div class = "comment-image">
				<p>{{ user.first_name.0 }}</p>
			</div>
			<input class = "field-input" type = "text" name = "comment" placeholder = "Add a comment...">
		</div>
	</div>
</div>

templates/blocks/product_row.html
{% load staticfiles %}

<div class = "product-row content-panel">
	<span style = "display: flex; align-items: baseline;">
		<a class = "content-title underline" href = "{{ more_link }}">{{ label }}</a>
		<a class = "content-subtitle link underline" href = "{{ more_link }}">See All</a>
	</span>
	<div class = "slider-container">
		<div class = "slider">
			{% for item in items %}
				{% include 'blocks/listing_item.html' with item=item vendor=vendor %}
			{% endfor %}
		</div>
	</div>
	<div class = "slide-left">
		<img src = "{% static 'img/icons/right-filled-48.png' %}">
	</div>
	<div class = "slide-right">
		<img src = "{% static 'img/icons/right-filled-48.png' %}">
	</div>
</div>

templates/blocks/promoted-tag.html
<span class = "promoted-tag {% if inverse %}inverse{% endif %}">Ad</span>

templates/blocks/search-page-numbers.html
{% load staticfiles %}

<div id = "page-numbers">
	<div id = "page-back-one" class = "page-number-container {% if page_num <= 1 %}disabled{% endif %}">
		{% if page_num > 1 %}
			<input id = "back-one-input" form = "{{ form_id }}" type = "text" name = "pg" value = "{{ page_num|add:'-1' }}" hidden>
		{% endif %}
		<img src = "{% static 'img/icons/right-slim-50.png' %}" style = "transform: rotate(180deg)">
	</div>
	<div id = "page-selector" class = "page-number-container">
		{% for i in bound %}
			<input onclick = "$('#{{ form_id }}').submit();" class = "page-number {% if i == page_num %}selected{% endif %}" form = "{{ form_id }}" type = "submit" name = "pg" value = {{ i }}>
		{% endfor %}
	</div>
	<div id = "page-forward-one" class = "page-number-container {% if page_num >= total_pages %}disabled{% endif %}">
		{% if page_num < total_pages %}
			<input id = "forward-one-input" form = "{{ form_id }}" type = "text" name = "pg" value = "{{ page_num|add:'1' }}" hidden>
		{% endif %}
		<img src = "{% static 'img/icons/right-slim-50.png' %}">
	</div>
</div>

templates/blocks/searchbar.html
{% load staticfiles %}

<form id = "{{ form_id }}" action = "{{ page }}" method = "GET">
	{% if search_bar %}
		<div id = "search-bar">
			<div id = "search-icon">
				<img src = "{% static 'img/icons/search-60.png' %}">
			</div>
			<input id = "search" class = "closed" form = "{{ form_id }}" name = "q" type = "text" placeholder = "Search for Products & Vendors" value = "{% if query is not None %}{{ query }}{% endif %}">
		</div>
	{% endif %}
</form>

templates/blocks/tag.html
<div class = "tag">{{ tag.name }}</div>