core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.feed, name='index'),
    path('feed', views.feed, name='feed'),
    path('store', views.store, name='store'),

    path('product/<slug>', views.product, name='product'),
    path('vendor/<slug>', views.vendor, name='vendor'),
    path('vendor/<slug>/feed', views.vendor_feed, name='vendor_feed'),
    path('vendor/<slug>/store', views.vendor_store, name='vendor_store'),
    path('vendor/<slug>/about', views.vendor_about, name='vendor_about'),

    path('search', views.search_view, name='search'),

    path('post/<int:id>', views.post, name = 'post'),

    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('cart/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund'),

    path('order/<ref_code>', views.OrderView.as_view(), name='order'),
    path('cancel-order/<ref_code>', views.cancel_order, name='cancel_order'),

    path('account/', views.account, name='account'),
    path('account/<str:page>', views.account_page, name='account_page'),
    path('change_password', views.change_password, name='change_password'),
    path('change_preferences', views.change_preferences, name='change_preferences'),
    path('delete_account', views.delete_account, name='delete_account'),

    path('landing/', views.landing, name='landing'),
    path('driver_signup/', views.driver_signup, name='driver_signup'),

    path('read-notifications', views.read_notifications, name = 'read_notifications'),
    path('clear-notifications', views.clear_notifications, name = 'clear_notifications'),

    path('follow-action/<slug>', views.follow_action, name = 'follow-action'),
    path('like-action/<int:id>', views.like_action, name = 'like-action'),
    path('comment', views.comment, name = 'comment'),
    path('comments/', views.comments, name = 'comments'),
    path('get_feed_posts/', views.get_feed_posts, name = 'get_feed_posts'),
]

dashboards/urls.py
from django.urls import path

from . import views

app_name = 'dashboards'

urlpatterns = [
    path('vendor/', views.vendor, name = 'vendor'),
    path('vendor/order/<str:ref_code>', views.vendor_order, name = 'vendor_order'),
    path('vendor/past_orders/<str:month>', views.vendor_past_month, name = 'vendor_past_month'),
    path('vendor/order_action', views.order_action, name = 'order_action'),
    path('vendor/<str:page>', views.vendor_page, name='vendor_page'),
    path('vendor/<str:page>/edit/<int:id>', views.edit_page, name='edit_page'),
    path('vendor/<str:page>/create', views.create_page, name='create_page'),
    path('vendor/<str:page>/delete/<slug:id>', views.delete_page, name='delete_page'),
    path('vendor/<str:page>/delete/<slug:id>', views.delete_page, name='delete_page'),

    path('vendor/approve-order/<ref_code>', views.approve_order, name='approve-order'),
    path('vendor/deny-order/<ref_code>', views.deny_order, name='deny-order'),

    path('driver', views.driver, name = 'driver'),
    path('driver/<str:page>', views.driver_page, name = 'driver_page'),
    path('driver/order/<str:ref_code>', views.order, name = 'order'),

    path('set-driver/<ref_code>', views.set_driver, name='set-driver'),
    path('set-delivered/<ref_code>', views.set_delivered, name='set_delivered'),
    path('unset-driver/<ref_code>', views.unset_driver, name='unset_driver'),
    path('cancel-order/<ref_code>', views.cancel_order, name='cancel_order'),

    path('admin', views.admin, name='admin'),
    path('admin/<str:page>', views.admin_page, name='admin_page'),
    path('admin/past_months/<str:month>', views.admin_past_month, name = 'admin_past_month'),
]

simntx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace = 'core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('db/', include('dashboards.urls', namespace = 'dashboards')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/account.html
{% extends "with_side_panel.html" %}
{% load account %}
{% load staticfiles %}

{% block title %}Account{% endblock %}

{% block with_side_panel_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/account.css' %}">

{% endblock %}

{% block left_panel %}
	
	<div class = "left-panel-group">
		<p class = "title">Account</p>
		<div class = "links">
			<a href = "{% url 'core:account' %}">
				<div class = "link {% block select_account %}selected{% endblock %}">
					<div class = "link-image">
						<img src = "{% static 'img/icons/home-color-48.png' %}">
					</div>
					<p>Account</p>
				</div>
			</a>
			<a href = "{% url 'core:account_page' 'password' %}">
				<div class = "link {% block select_password %}{% endblock %}">
					<div class = "link-image">
						<img src = "{% static 'img/icons/lock-color-48.png' %}">
					</div>
					<p>Password</p>
				</div>
			</a>
			<a href = "{% url 'core:account_page' 'orders' %}">
				<div class = "link {% block select_orders %}{% endblock %}">
					<div class = "link-image">
						<img src = "{% static 'img/icons/products-color-48.png' %}">
					</div>
					<p>Orders</p>
				</div>
			</a>
			<a href = "{% url 'core:account_page' 'notifications' %}">
				<div class = "link {% block select_notifications %}{% endblock %}">
					<div class = "link-image">
						<img src = "{% static 'img/icons/bell-color-48.png' %}">
					</div>
					<p>Notifications</p>
				</div>
			</a>
		</div>
	</div>
	<div class = "left-panel-group">
		<div class = "links">
			<a href = "{% url 'core:account_page' 'delete' %}">
				<div id = "delete" class = "link {% block select_delete %}{% endblock %}">
					<div class = "link-image">
						<img src = "{% static 'img/icons/trash-color-48.png' %}">
					</div>
					<p style = "color: red; font-family: Roboto-Medium;">Delete Account</p>
				</div>
			</a>
		</div>
	</div>

{% endblock %}

{% block right_panel %}

	<div class = "right-panel-group content-panel-container">
		<div class = "header">
			<p class = "name">Account</p>
		</div>
		<div class = "section">
			<form method = 'POST'>
				{% csrf_token %}
			
				<div class = "form-field row">
					<p class = "field-label">Name</p>
					<div class = "field-inputs">
						<input class = "field-input" type = "text" name = "first_name" placeholder = "First Name" value = "{{ user.first_name }}" required>
						<input class = "field-input" type = "text" name = "last_name" placeholder = "Last Name" value = "{{ user.last_name }}" required>
					</div>
				</div>
				<div class = "form-field row">
					<p class = "field-label">Email</p>
					<div class = "field-inputs">
						<input class = "field-input" type = "email" name = "email" placeholder = "Email" value = "{{ user.email }}" required>
					</div>
				</div>
				<div class = "form-end end">
					<input class = "form-submit small" type = "submit" value = "Save">
				</div>
			</form>
		</div>
	</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Home{% endblock %} - Simntx</title>
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/base.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/nav.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/nav-desktop.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/nav-mobile.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/media_queries.css' %}">
	
	<style>
		@font-face {
			font-family: Roboto-Thin;
			src: url({% static 'font/roboto/Roboto-Thin.ttf' %});
		}
		@font-face {
			font-family: Roboto-Regular;
			src: url({% static 'font/roboto/Roboto-Regular.ttf' %});
		}
		@font-face {
			font-family: Roboto-Medium;
			src: url({% static 'font/roboto/Roboto-Medium.ttf' %});
		}
	</style>
	
	{% block css %}
	{% endblock %}
</head>
<body>
	{% include 'blocks/nav.html' %}
	
	<div id = "container">
		<div id = "left-panel">
			{% block left_base_panel %}
			{% endblock %}
		</div>
		<div id = "right-panel">
			{% block right_panel %}
			{% endblock %}
		</div>
	</div>
	
	{% include 'blocks/footer.html' %}
	
	<script type = "text/javascript" src = "{% static 'js/jquery.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/ajax.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/base.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/nav.js' %}"></script>
	
	{% block js %}
	{% endblock %}
</body>
</html>

templates/checkout.html
{% extends "home.html" %}

{% load staticfiles %}
{% load countries %}

{% block title %}Checkout{% endblock %}

{% block home_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/checkout.css' %}">

{% endblock %}

{% block right_panel %}

	<div class = "content-panel-container content-grid two inverse" style = "--side-panel-width: 300px;">
		<div class = "content-container">
			<div class = "content-panel">
				<form method = "POST">
					{% csrf_token %}
					
					<p class = "content-title large">Checkout</p>
					<div class = "form-group separator">
						<p class = "group-title">Shipping Address</p>
						<div class = "hideable_shipping_form">
							<div class = "form-field">
								<input class = "field-input" id = "shipping_address" type = "text" name = "shipping_address" placeholder = "Address">
							</div>
							<div class = "form-field">
								<input class = "field-input" id = "shipping_address2" type = "text" name = "shipping_address2" placeholder = "Address 2 (optional)">
							</div>
							<div class = "form-group row">
								<div class = "form-field half">
									<p class = "field-label">Country</p>
									<select id = "id_shipping_country" class = "field-input custom-select d-block w-100" name = "shipping_country">
										<option value = "US" selected>(select country)</option>
										
										{% get_countries as countries %}
										{% for country in countries %}
											<option value="{{ country.code }}">{{ country.name }}</option>
										{% endfor %}
									</select>
								</div>
								<div class = "form-field half">
									<p class = "field-label">Zip Code</p>
									<input id = "shipping_zip" class = "field-input" type = "text" name = "shipping_zip" placeholder = "Zip">
								</div>
							</div>
							<div class = "form-field row left">
								<input class = "form-checkbox" id = "same_billing_address" type = "checkbox" name = "same_billing_address">
								<label for = "same_billing_address">Use for billing address</label>
							</div>
							<div class = "form-field row left">
								<input class = "form-checkbox" id = "set_default_shipping" type = "checkbox" name = "set_default_shipping">
								<label for = "set_default_shipping">Save as default shipping address</label>
							</div>
						</div>
					</div>
					{% if default_shipping_address %}
						<div class = "form-field row left">
							<input type = "checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
							<label class = "custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address }}</label>
						</div>
					{% endif %}
					<div class = "form-group separator">
						<p class = "group-title">Billing Address</p>
						<div class = "hideable_billing_form">
							<div class = "form-field">
								<input class = "field-input" id = "billing_address" type = "text" name = "billing_address" placeholder = "Address">
							</div>
							<div class = "form-field">
								<input class = "field-input" id = "billing_address2" type = "text" name = "billing_address2" placeholder = "Address 2 (optional)">
							</div>
							<div class = "form-group row">
								<div class = "form-field half">
									<p class = "field-label">Country</p>
									<select id = "id_billing_country" class = "field-input custom-select d-block w-100" name = "billing_country">
										<option value = "US" selected>(select country)</option>
										
										{% for country in countries %}
											<option value="{{ country.code }}">{{ country.name }}</option>
										{% endfor %}
									</select>
								</div>
								<div class = "form-field half">
									<p class = "field-label">Zip Code</p>
									<input id = "billing_zip" class = "field-input" type = "text" name = "billing_zip" placeholder = "Zip">
								</div>
							</div>
							<div class = "form-field row left">
								<input class = "form-checkbox" id = "set_default_billing" type = "checkbox" name = "set_default_billing">
								<label for = "set_default_billing">Save as default billing address</label>
							</div>
						</div>
						{% if default_billing_address %}
							<div class = "form-field row left">
								<input type = "checkbox" class = "form-checkbox" name = "use_default_billing" id = "use_default_billing">
								<label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address }}</label>
							</div>
						{% endif %}
					</div>
					<div class = "form-group separator">
						<p class = "group-title">Payment Option</p>
						<div class = "form-field row left">
							<input id = "Credit card/Debit Card" class = "form-checkbox" id = "payment_option" type = "radio" name = "payment_option" value = "S">
							<label for = "Credit card/Debit Card">Credit card/Debit card</label>
						</div>
					</div>
					<div class = "form-group separator">
						<input id = "checkout-submit" class = "form-submit" type = "submit" value = "Checkout">
					</div>
				</form>
			</div>
		</div>
		<div class = "content-container main">
			<div class = "content-panel">
				{% get_active_order_items user as order_items %}
				{% include "order_snippet.html" with items=order_items %}
			</div>
		</div>
	</div>

{% endblock %}

{% block home_js %}
<script>
	var hideable_shipping_form = $('.hideable_shipping_form');
	var hideable_billing_form = $('.hideable_billing_form');

	var use_default_shipping = $("#use_default_shipping");
	var use_default_billing = $("#use_default_billing");

	use_default_shipping.on('change', function() {
		if (this.checked) {
			hideable_shipping_form.hide();
		} else {
			hideable_shipping_form.show();
		}
	});

	use_default_billing.on('change', function() {
		if (this.checked) {
			hideable_billing_form.hide();
		} else {
			hideable_billing_form.show();
		}
	});

</script>
{% endblock %}

templates/home.html
{% extends 'with_side_panel.html' %}

{% load staticfiles %}

{% block with_side_panel_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/home.css' %}">

	{% block home_css %}
	{% endblock %}

{% endblock %}

{% block home_button %}{% endblock %}

{% block left_panel %}

	<div class = "left-panel-group">
		<p class = "title">General</p>
		<div class = "links">
			<a href = "{% url 'core:feed' %}">
				<div class = "link {% block select_feed %}{% endblock %}">
					<div class = "link-image">
						<img src = {% block select_feed_img %}"{% static 'img/icons/home-color-48.png' %}"{% endblock %}>
					</div>
					<p>Feed</p>
				</div>
			</a>
			<a href = "{% url 'core:store' %}">
				<div class = "link {% block select_store %}{% endblock %}">
					<div class = "link-image">
						<img src = {% block select_store_img %}"{% static 'img/icons/store-color-48.png' %}"{% endblock %}>
					</div>
					<p>Store</p>
				</div>
			</a>
		</div>
	</div>
	<div class = "left-panel-group">
		<p class = "title">Account</p>
		<div class = "links">
			{% if user.userprofile.vendor_owner %}
				<a href = "{% url 'dashboards:vendor' %}">
					<div class = "link {% block select_vendor %}{% endblock %}">
						<div class = "link-image">
							<img src = {% block select_vendor_img %}"{% static 'img/icons/dashboard-color-48.png' %}"{% endblock %}>
						</div>
						<p>Vendor Profile</p>
					</div>
				</a>
			{% endif %}
			{% if user.userprofile.is_driver %}
				<a href = "{% url 'dashboards:driver' %}">
					<div class = "link {% block select_drivers %}{% endblock %}">
						<div class = "link-image">
							<img src = {% block select_drivers_img %}"{% static 'img/icons/drivers-color-48.png' %}"{% endblock %}>
						</div>
						<p>Driver Dashboard</p>
					</div>
				</a>
			{% endif %}
			{% if user.is_staff %}
				<a href = "{% url 'dashboards:admin' %}">
					<div class = "link">
						<div class = "link-image">
							<img src = "{% static 'img/icons/dashboard-color-48.png' %}">
						</div>
						<p>Admin Dashboard</p>
					</div>
				</a>
			{% endif %}
			
			<a href = "{% url 'core:account' %}">
				<div class = "link {% block select_account %}{% endblock %}">
					<div class = "link-image">
						<img src = {% block select_account_img %}"{% static 'img/icons/settings-color-48.png' %}"{% endblock %}>
					</div>
					<p>Settings</p>
				</div>
			</a>
		</div>
	</div>

{% endblock %}

{% block right_panel %}
{% endblock %}

{% block with_side_panel_js %}

	{% block home_js %}
	{% endblock %}

{% endblock %}

templates/messages.html
<div id = "message-container">
	<div class = "safe-div">
		{% if messages %}
			{% for message in messages %}
				<div class = "message {{ messages.tags }}" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</div>

templates/order.html
{% extends "home.html" %}

{% load staticfiles %}

{% block title %}Order Overview{% endblock %}

{% block home_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/cart.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/checkout.css' %}">
	
{% endblock %}

{% block right_panel %}

	<div class = "content-panel-container content-grid two inverse" style = "--side-panel-width: 300px;">
		<div class = "content-container">
			<div class = "content-panel">
				<div class = "header" style = "display: flex; align-items: baseline;">
					<p class = "content-title large">Order #{{ order.ref_code }}</p>
					<p class = "content-subtitle">{% if order.cancelled %}Cancelled
												  {% elif order.refund_granted %}Refunded
												  {% elif order.refund_requested %}Refund Requested
												  {% elif order.authorized %}Approved
												  {% elif order.denied %}Denied
												  {% endif %}</p>
				</div>
				<div class = "section">
					<table>
						<tbody>
							<tr>
								<th>Product</th>
								<th>Vendor</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Total Price</th>
							</tr>
							{% for product in items.all %}
								<tr {% if not product.in_stock %}style = "opacity: .3;" title = "Out of Stock"{% endif %}>
									<td>{{ product.item.title }}</td>
									<td>{{ product.item.vendor }}</td>
									<td>{{ product.item.price }}</td>
									<td>{{ product.quantity }}</td>
									<td>
										{% if order_item.item.discount_price %}
											{{ product.get_total_discount_item_price }}
										{% else %}
											{{ product.get_total_item_price }}
										{% endif %}
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class = "content-container main">
			<div class = "content-panel">
				{% include "order_snippet.html" with order=order items=items %}
		</div>
	</div>

{% endblock %}

templates/order_snippet.html
<div class = "header" style = "display: flex; align-items: baseline;">
	<p class = "content-title large">Order</p>
	<p class = "content-subtitle">{% get_order_count items as order_count %}{{ order_count }} item{% if order_count != 1 %}s{% endif %}</p>
</div>
<div class = "cart-items">
	{% for item in items %}
		{% if item.in_stock %}
			<div class = "cart-item">
				<div class = "item-details">
					<p class = "title">{{ item.item.title }}</p>
					<p class = "quantity">x{{ item.quantity }}</p>
				</div>
				<p class = "price">${{ item.get_final_price }}</p>
			</div>
		{% endif %}
	{% endfor %}
</div>
<hr>

{% if order.coupon %}
	<div class = "cart-coupons">
		<p class = "title">Coupons</p>
		<div class = "coupon">
			<p class = "title">{{ order.coupon.code }}</p>
			<p class = "amount price">-${{ order.coupon.amount }}</p>
		</div>
	</div>
	<hr>
{% endif %}

<div class = "cart-final-prices">
	<div class = "cart-item">
		<div class = "item-details">
			<p class = "title">Delivery Fee</p>
		</div>
		<p class = "price">$5.00</p>
	</div>
	<div class = "cart-total">
		<p class = "title">Total (USD)</p>
		<p class = "price">${{ order.get_total }}</p>
	</div>
</div>

{% if DISPLAY_COUPON_FORM %}
	<form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
		{% csrf_token %}
		
		<div class = "form-field row">
			<input id = "id_code" class = "field-input" type = "text" name = "code" placeholder = "Promo code">
			<input class = "form-submit" type = "submit" value = "Apply">
		</div>
	</form>
{% endif %}

templates/order_summary.html
{% extends "home.html" %}

{% load staticfiles %}

{% block title %}Cart{% endblock %}

{% block home_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/cart.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/checkout.css' %}">
	
{% endblock %}

{% block right_panel %}
	
	<div class = "content-panel-container content-grid inverse two" style = "--side-panel-width: 300px;">
		<div class = "content-container">
			<div class = "content-panel">
				<p class = "content-title large">Cart</p>
				<table>
					<tbody>
						<tr>
							<th>Product</th>
							<th>Vendor</th>
							<th>Price</th>
							<th>Quantity</th>
							<th>Tax</th>
							<th>Total Price</th>
							<th></th>
						</tr>
						
						{% get_active_order_items user as order_items %}
						{% for product in order_items.all %}
							<tr>
								<td>{{ product.item.title }}</td>
								<td>{{ product.item.vendor.title }}</td>
								<td>{{ product.item.price }}</td>
								<td>
									<a href="{% url 'core:remove-single-item-from-cart' product.item.slug %}">
										<img class = "tiny-button" src = "{% static 'img/icons/minus-30.png' %}">
									</a>
									{{ product.quantity }}
									<a href="{% url 'core:add-to-cart' product.item.slug %}">
										<img class = "tiny-button" src = "{% static 'img/icons/plus-30.png' %}">
									</a>
								</td>
								<td>
									{% if order_item.item.discount_price %}
										{{ product.get_discount_tax }}
									{% else %}
										{{ product.get_tax }}
									{% endif %}
								</td>
								<td>
									{% if order_item.item.discount_price %}
										{{ product.get_total_discount_item_price }}
									{% else %}
										{{ product.get_total_item_price }}
									{% endif %}
								</td>
								<td>
									<a href="{% url 'core:remove-from-cart' product.item.slug %}">
										<img class = "tiny-button remove" src = "{% static 'img/icons/trash-24.png' %}">
									</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
				
				{% get_cart_count user as cart_count %}
				{% if cart_count == 0 %}
					<div class = "form-end">
						<a href = "{% url 'core:store' %}">
							<input id = "continue-shopping" class = "form-submit" type = "submit" value = "Continue Shopping">
						</a>
					</div>
				{% else %}
					<div class = "form-end">
						<a href = "{% url 'core:checkout' %}">
							<input class = "form-submit" type = "submit" value = "Checkout">
						</a>
					</div>
				{% endif %}
			</div>
		</div>
		<div class = "content-container">
			<div class = "content-panel">
			{% comment %}
			Somthing is wrong with this and im not being payed anymore
			 {% get_cart_count user as cart_count_two %}
			{% if cart_count_two == 0 %}
				{% include "order_snippet.html" with items=order_items %}
			{% endif %} {% endcomment %}
			</div>
		</div>
	</div>

{% endblock %}

templates/search.html
{% extends 'home.html' %}

{% load staticfiles %}

{% block title %}{% if query %}{{ query }}{% else %}Search{% endif %}{% endblock %}

{% block home_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/search.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/listings.css' %}">

{% endblock %}

{% block right_panel %}

	<div class = "content-panel-container">
		<div id = "search-bar-container" class = "content-panel">
			{% url 'core:search' as page %}
			{% include 'blocks/searchbar.html' with query=query page=page search_bar=True form_id='search-form' %}
		</div>
		<div id = "search-details-container" class = "content-grid two">
			<div id = "filters-container" class = "content-panel">
				<p class = "content-title">Filters</p>
				
				{% with 'search-form' as form_id %}
					{% include 'blocks/filters/type.html' with form_id=form_id type=type %}
					{% include 'blocks/filters/tags.html' with form_id=form_id all_tags=all_tags %}
					{% include 'blocks/filters/price.html' with form_id=form_id price=price %}
				{% endwith %}
			</div>
			
			<div id = "results-container" class = "content-panel">
				<span class = "content-title">
					Products
					<p class = "content-subtitle"> Results {{ shown_lower }}-{{ shown_upper }} of {{ total_results }}</p>
				</span>
				<div class = "products-container four">
					{% if type == 'vendors' %}
						{% for item in results %}
							{% include 'blocks/listing_item.html' with item=item vendor=True grid_item=True show_promotions=True %}
						{% endfor %}
					{% else %}
						{% for item in results %}
							{% include 'blocks/listing_item.html' with item=item vendor=None grid_item=True show_promotions=True %}
						{% endfor %}
					{% endif %}
				</div>
				
				{% include 'blocks/search-page-numbers.html' with page_num=page_num total_pages=total_pages bound=bound form_id="search-form" %}
			</div>
		</div>
	</div>

{% endblock %}

{% block js %}
	
	<script type = "text/javascript" src = "{% static 'js/listings.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/search.js' %}"></script>
	<script type = "text/javascript" src = "{% static 'js/search_helper.js' %}"></script>
	
{% endblock %}

templates/with_side_panel.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/with_side_panel.css' %}">

	{% block with_side_panel_css %}
	{% endblock %}

{% endblock %}

{% block left_base_panel %}
	
	{% block home_button %}
		
		<a href = "{% url 'core:index' %}">
			<div class = "left-panel-group back">
				<img src = "{% static 'img/icons/back-color-48.png' %}">
				<p class = "back-title">Back</p>
			</div>
		</a>
	
	{% endblock %}

	{% block left_panel %}
	{% endblock %}

{% endblock %}

{% block right_panel %}
{% endblock %}

{% block js %}

	{% block with_side_panel_js %}
	{% endblock %}

{% endblock %}