core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.feed, name='index'),
    path('feed', views.feed, name='feed'),
    path('store', views.store, name='store'),

    path('product/<slug>', views.product, name='product'),
    path('vendor/<slug>', views.vendor, name='vendor'),
    path('vendor/<slug>/feed', views.vendor_feed, name='vendor_feed'),
    path('vendor/<slug>/store', views.vendor_store, name='vendor_store'),
    path('vendor/<slug>/about', views.vendor_about, name='vendor_about'),

    path('search', views.search_view, name='search'),

    path('post/<int:id>', views.post, name = 'post'),

    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('cart/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund'),

    path('order/<ref_code>', views.OrderView.as_view(), name='order'),
    path('cancel-order/<ref_code>', views.cancel_order, name='cancel_order'),

    path('account/', views.account, name='account'),
    path('account/<str:page>', views.account_page, name='account_page'),
    path('change_password', views.change_password, name='change_password'),
    path('change_preferences', views.change_preferences, name='change_preferences'),
    path('delete_account', views.delete_account, name='delete_account'),

    path('landing/', views.landing, name='landing'),
    path('driver_signup/', views.driver_signup, name='driver_signup'),

    path('read-notifications', views.read_notifications, name = 'read_notifications'),
    path('clear-notifications', views.clear_notifications, name = 'clear_notifications'),

    path('follow-action/<slug>', views.follow_action, name = 'follow-action'),
    path('like-action/<int:id>', views.like_action, name = 'like-action'),
    path('comment', views.comment, name = 'comment'),
    path('comments/', views.comments, name = 'comments'),
    path('get_feed_posts/', views.get_feed_posts, name = 'get_feed_posts'),
]

dashboards/urls.py
from django.urls import path

from . import views

app_name = 'dashboards'

urlpatterns = [
    path('vendor/', views.vendor, name = 'vendor'),
    path('vendor/order/<str:ref_code>', views.vendor_order, name = 'vendor_order'),
    path('vendor/past_orders/<str:month>', views.vendor_past_month, name = 'vendor_past_month'),
    path('vendor/order_action', views.order_action, name = 'order_action'),
    path('vendor/<str:page>', views.vendor_page, name='vendor_page'),
    path('vendor/<str:page>/edit/<int:id>', views.edit_page, name='edit_page'),
    path('vendor/<str:page>/create', views.create_page, name='create_page'),
    path('vendor/<str:page>/delete/<slug:id>', views.delete_page, name='delete_page'),
    path('vendor/<str:page>/delete/<slug:id>', views.delete_page, name='delete_page'),

    path('vendor/approve-order/<ref_code>', views.approve_order, name='approve-order'),
    path('vendor/deny-order/<ref_code>', views.deny_order, name='deny-order'),

    path('driver', views.driver, name = 'driver'),
    path('driver/<str:page>', views.driver_page, name = 'driver_page'),
    path('driver/order/<str:ref_code>', views.order, name = 'order'),

    path('set-driver/<ref_code>', views.set_driver, name='set-driver'),
    path('set-delivered/<ref_code>', views.set_delivered, name='set_delivered'),
    path('unset-driver/<ref_code>', views.unset_driver, name='unset_driver'),
    path('cancel-order/<ref_code>', views.cancel_order, name='cancel_order'),

    path('admin', views.admin, name='admin'),
    path('admin/<str:page>', views.admin_page, name='admin_page'),
    path('admin/past_months/<str:month>', views.admin_past_month, name = 'admin_past_month'),
]

simntx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace = 'core')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('db/', include('dashboards.urls', namespace = 'dashboards')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

dashboards/models.py
from django.db import models

# Create your models here.

dashboards/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User

from core.models import *

class EditVendorForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = ['title', 'description', 'profile_image', 'cover_image', 'phone_number']

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']

class EditProductForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset = GeneralTag.objects.all())

    class Meta:
        model = Item
        fields = ['title', 'description', 'image', 'price', 'discount_price', 'tags']

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']

    def __init__(self, vendor, *args, **kwargs):
        self.vendor = vendor

        super(CreatePostForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(CreatePostForm, self).save(commit=False)
        instance.vendor = self.vendor

        if commit:
            instance.save()

        return instance

class CreateProductForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=GeneralTag.objects.all())

    class Meta:
        model = Item
        fields = ['title', 'description', 'price', 'discount_price', 'image', 'tags']

    def __init__(self, vendor, *args, **kwargs):
        self.vendor = vendor

        super(CreateProductForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(CreateProductForm, self).save(commit=False)
        instance.vendor = self.vendor

        if commit:
            instance.save()

        return instance

dashboards/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse
from django.template.loader import get_template
from django.contrib import messages
from django.utils import timezone

from core.models import *
from core.views import get_general_tags, get_vendors, can_create_promotion

from datetime import datetime, date, timedelta

from . import forms
from core import notifications

import stripe

def vendor(request):
    data = {}
    
    vendor = get_vendors(request.user.userprofile)
    vendor.general_tags = get_general_tags(vendor)

    if request.method == 'POST':
        form = forms.EditVendorForm(request.POST, request.FILES, instance = vendor)

        print(request.POST)

        if form.is_valid():
            v = form.save()

            if v.address:
                v.address.delete()

            if v.hours:
                v.hours.delete()

            address = Address(street_address = request.POST['street_address'],
                              country = request.POST['country'],
                              zip = request.POST['zip'])

            hours = VendorHours(sunday_start = datetime.strptime(request.POST['sunday_start'], '%H:%S'),
                                  sunday_end = datetime.strptime(request.POST['sunday_end'], '%H:%S'),
                                  monday_start = datetime.strptime(request.POST['monday_start'], '%H:%S'),
                                  monday_end = datetime.strptime(request.POST['monday_end'], '%H:%S'),
                                  tuesday_start = datetime.strptime(request.POST['tuesday_start'], '%H:%S'),
                                  tuesday_end = datetime.strptime(request.POST['tuesday_end'], '%H:%S'),
                                  wednesday_start = datetime.strptime(request.POST['wednesday_start'], '%H:%S'),
                                  wednesday_end = datetime.strptime(request.POST['wednesday_end'], '%H:%S'),
                                  thursday_start = datetime.strptime(request.POST['thursday_start'], '%H:%S'),
                                  thursday_end = datetime.strptime(request.POST['thursday_end'], '%H:%S'),
                                  friday_start = datetime.strptime(request.POST['friday_start'], '%H:%S'),
                                  friday_end = datetime.strptime(request.POST['friday_end'], '%H:%S'),
                                  saturday_start = datetime.strptime(request.POST['saturday_start'], '%H:%S'),
                                  saturday_end = datetime.strptime(request.POST['saturday_end'], '%H:%S'))

            address.save()
            hours.save()

            v.hours = hours
            v.address = address

            v.save()
        else:
            print(form.errors)

    data['vendor'] = vendor

    return render(request, 'dashboards/vendor.html', data)


def vendor_page(request, page, month=date.today()):
    data = {}

    vendor = get_vendors(request.user.userprofile)

    template = 'dashboards/vendor/' + page + '.html'

    if not is_template(template):
        return redirect('dashboards:vendor')

    if page == 'posts':
        posts = Post.objects.filter(vendor = vendor).order_by('-posted')

        data['posts'] = posts
    elif page == 'products':
        print('products')

        products = Item.objects.filter(vendor = vendor)

        data['products'] = products
    elif page == 'approve_orders':
        month_balance = 0

        orders = Order.objects.filter(ordered = True, authorized = False, denied = False, cancelled = False, vendor = vendor)
        month_orders = Order.objects.filter(ordered = True, authorized = True, cancelled = False, vendor = vendor, ordered_date__date__month = datetime.today().month)

        for order in month_orders.all():
            month_balance += order.get_vendor_keep()

        data['orders'] = orders
        data['num_orders'] = month_orders.count()
        data['amount_orders'] = month_balance
    elif page == 'past_orders':
        month_balance = 0

        month_orders = Order.objects.filter(ordered = True, authorized = True, cancelled = False, vendor = vendor, ordered_date__date__month = month.month, ordered_date__date__year = month.year)

        for order in month_orders.all():
            month_balance += order.get_vendor_keep()

        back_month = (month.replace(day = 1) - timedelta(days = 1))
        forward_month = (month.replace(day = 1) + timedelta(days = 40))

        data['orders'] = month_orders
        data['month'] = month.strftime('%B')
        data['year'] = month.year
        data['num_orders'] = month_orders.count()
        data['amount_orders'] = month_balance

        data['back_month'] = back_month.strftime('%m%Y')
        data['forward_month'] = forward_month.strftime('%m%Y')

        data['back_name'] = back_month.strftime('%B')
        data['forward_name'] = forward_month.strftime('%B')
    elif page == 'promotions':
        promotions = list(StorePromotion.objects.filter(vendor = vendor)) + \
                     list(ProductPromotion.objects.filter(vendor = vendor)) + \
                     list(PostPromotion.objects.filter(vendor=vendor))

        data['promotions'] = promotions

    data['vendor'] = vendor

    print(template)

    return render(request, template, data)


def vendor_past_month(request, month):
    return vendor_page(request, 'past_orders', month=date(int(month[-4:]), int(month[:-4]), 1))


def order_action(request):
    print(request.POST)

    if request.POST:
        if 'action' in request.POST:
            if request.POST.get('action').lower() == 'approve':
                if 'ref_code' in request.POST:
                    order = Order.objects.filter(ref_code=request.POST.get('ref_code'))

                    if order.exists():
                        order = order[0]

                        products = [int(product) for product in request.POST.getlist('products')]

                        exclusions = OrderItem.objects.filter(order = order).exclude(id__in = products)

                        print('Exclusions: ' + str(exclusions))

                        return approve_order(request, order.ref_code, exclusions)
            elif request.POST.get('action').lower() == 'deny':
                #return deny_order(request, )
                pass

    return redirect('dashboards:vendor_page', page='approve_orders')


# Function : approve delivery
# This function is used by vendors to aprove a delivery and
# allow a driver too assigan the delivery
def approve_order(request, ref_code, exclusions=None):
    order = Order.objects.filter(ref_code=ref_code)

    if order.exists() and not order[0].authorized:
        order = order[0]

        if exclusions:
            for product in exclusions:
                product.in_stock = False
                product.save()

        order.authorized = True
        order.save()

        charge = chargeUser(request, order)

        if charge[0]:
            notifications.order_approved_denied(order.user, order.ref_code, True)
        else:
            notifications.order_cancelled(order.user, order.ref_code, charge[1])

    return redirect('dashboards:vendor_page', page='approve_orders')


def deny_order(request, ref_code):
    order = Order.objects.filter(ref_code=ref_code)

    if order.exists() and not order[0].authorized:
        order = order[0]

        order.denied = True
        order.save()

        notifications.order_approved_denied(order.user, order.ref_code, False)

    return redirect('dashboards:vendor_page', page='approve_orders')


def chargeUser(request, order):
    warning = ''

    try:
        amount = int(order.get_total() * 100)

        charge = stripe.Charge.create(amount=amount, currency="usd", customer=order.user.userprofile.stripe_customer_id)

        payment = Payment()
        payment.stripe_charge_id = charge['id']
        payment.user = order.user
        payment.amount = charge['amount']
        payment.save()

        order.payment = payment
        order.save()

        return True, True
    except stripe.error.CardError as e:
        body = e.json_body

        err = body.get('error', {})

        warning = f"{err.get('message')}"
    except stripe.error.RateLimitError as e:
        # Too many requests made to the API too quickly
        warning = "Rate limit error"
    except stripe.error.InvalidRequestError as e:
        # Invalid parameters were supplied to Stripe's API
        print(e)

        warning = "Invalid parameters"
    except stripe.error.AuthenticationError as e:
        # Authentication with Stripe's API failed
        # (maybe you changed API keys recently)
        warning = "Not authenticated"
    except stripe.error.APIConnectionError as e:
        # Network communication with Stripe failed
        warning = "Network error"
    except stripe.error.StripeError as e:
        # Display a very generic error to the user, and maybe send
        # yourself an email
        warning = "Something went wrong. You were not charged. Please try again."
    except Exception as e:
        # send an email to ourselves
        warning = "A serious error occurred. We have been notifed."

        print(e)

    return False, warning


def edit_page(request, page, id):
    data = {}

    if request.method == 'POST':
        if page == 'posts':
            form = forms.EditPostForm(request.POST)

            if form.is_valid():
                post = Post.objects.get(id = id)
                post.text = form.cleaned_data['text']

                print(request.POST)

                if 'link-urls' in request.POST:
                    post.links.all().delete()

                    names = request.POST.getlist('link-names')
                    urls = request.POST.getlist('link-urls')

                    for i in range(len(urls)):
                        name = names[i]
                        url = urls[i]

                        if url != "" and url is not None:

templates/dashboards/driver/completed.html
{% extends 'dashboards/driver.html' %}

{% load staticfiles %}

{% block title %}Completed Deliveries{% endblock %}

{% block select_outstanding %}{% endblock %}
{% block select_completed %}selected{% endblock %}

{% block right_panel %}

	<div class = "right-panel-group content-panel-container">
		<div class = "header">
			<p class = "name">Completed Deliveries</p>
		</div>
		<div class = "section table">
			<table class = "data-table">
				<tbody>
					<tr class = "header-row">
						<th>#</th>
						<th>Ordered</th>
						<th>Address</th>
						<th>Summary</th>
					</tr>
					
					{% for order in orders %}
						<tr>
							<td>{{ order.ref_code }}</td>
							<td>{{ order.ordered_date }}</td>
							<td>{{ order.shipping_address.street_address }}</td>
							<td class = "action-col">
								<a href = "{% url 'dashboards:order' order.ref_code %}">
									<div class = "action view" title = "View">
										<img src = "{% static 'img/icons/eye-48.png' %}">
									</div>
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

templates/dashboards/driver/current.html
{% extends 'dashboards/driver.html' %}

{% load staticfiles %}

{% block title %}Current Deliveries{% endblock %}

{% block select_outstanding %}{% endblock %}
{% block select_current %}selected{% endblock %}

{% block right_panel %}

	<div class = "right-panel-group content-panel-container">
		<div class = "header">
			<p class = "name">Current Deliveries</p>
		</div>
	<div class = "section table">
			<table class = "data-table">
				<tbody>
					<tr class = "header-row">
						<th>#</th>
						<th>Ordered</th>
						<th>Address</th>
						<th>Summary</th>
					</tr>
					
					{% for order in orders %}
						<tr>
							<td>{{ order.ref_code }}</td>
							<td>{{ order.ordered_date }}</td>
							<td>{{ order.shipping_address.street_address }}</td>
							<td class = "action-col">
								<a href = "{% url 'dashboards:order' order.ref_code %}">
									<div class = "action view" title = "View">
										<img src = "{% static 'img/icons/eye-48.png' %}">
									</div>
								</a>
								<a href = "{% url 'dashboards:set_delivered' order.ref_code %}">
									<div class = "action accept" title = "Mark Delivered">
										<img src = "{% static 'img/icons/check-48.png' %}">
									</div>
								</a>
								<a href = "{% url 'dashboards:unset_driver' order.ref_code %}">
									<div class = "action delete" title = "Cancel Delivery">
										<img src = "{% static 'img/icons/delete-red-24.png' %}" style = "--grayscale: 100%; --brightness: 0%;">
									</div>
								</a>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

{% endblock %}

templates/dashboards/driver/order.html
{% extends "dashboards/driver.html" %}

{% load staticfiles %}
{% load tags %}

{% block title %}Order Overview{% endblock %}

{% block driver_css %}

	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/checkout.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/cart.css' %}">
	
{% endblock %}

{% block right_panel %}

	<div class = "content-panel-container content-grid two inverse" style = "--side-panel-width: 300px;">
		<div class = "content-container">
			<div class = "content-panel">
				<div class = "header" style = "display: flex; align-items: baseline;">
					<p class = "content-title large">Order #{{ order.ref_code }}</p>
					<p class = "content-subtitle">{% if order.cancelled %}Cancelled
												  {% elif order.refund_granted %}Refunded
												  {% elif order.being_delivered %}Being Delivered
												  {% elif order.delivered %}Delivered
												  {% endif %}</p>
				</div>
				<div class = "section">
					<table>
						<tbody>
							<tr>
								<th>Product</th>
								<th>Vendor</th>
								<th>Price</th>
								<th>Quantity</th>
								<th>Total Price</th>
							</tr>
							{% get_order_items order.ref_code as items %}
							{% for product in items.all %}
								<tr {% if not product.in_stock %}style = "opacity: .3;" title = "Out of Stock"{% endif %}>
									<td>{{ product.item.title }}</td>
									<td>{{ product.item.vendor }}</td>
									<td>{{ product.item.price }}</td>
									<td>{{ product.quantity }}</td>
									<td>
										{% if order_item.item.discount_price %}
											{{ product.get_total_discount_item_price }}
										{% else %}
											{{ product.get_total_item_price }}
										{% endif %}
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
			
					{% if order.authorized and not order.cancelled and not order.refund_granted and not order.delivered and request.user.userprofile == order.driver %}
						<div class = "form-end start">
							{% if order.being_delivered %}
								<a href = "{% url 'core:set_delivered' order.ref_code %}">
									<input class = "form-submit" type = "submit" value = "Mark Delivered">
								</a>
							{% else %}
								<a href = "{% url 'core:set-driver' order.ref_code %}">
									<input class = "form-submit" type = "submit" value = "Accept" style = "background-color: var(--green);">
								</a>
							{% endif %}
						</div>
					{% endif %}
				</div>
			</div>
		</div>
		<div class = "content-container main">
			<div class = "content-panel">
				{% include "order_snippet.html" with order=order items=items %}
			</div>
			<div class = "content-panel">
				{% include "blocks/order_keep.html" with order=order items=items vendor_view=False %}
			</div>
		</div>
	</div>

{% endblock %}

{% block js %}

	<script>
		function goBack() {
		  window.history.back();
		}
	</script>
	
{% endblock %}